### ISSUE TITLE
Omics Paperkriterien

### ISSUE THREAD

**Issue by JulianDietz** [ChristophToegel/PS-TextMining#27]
Bisher werden aus allen Kategorien alle Journals mit allen Paper aus 2018 gespeichert.
Einschränkungen nach
* Jahr
* Impact factor des Journals
* Art des Artikels
* Abstract vorhanden oder nicht
* Full Text vorhanden oder nicht

**Comment by AnnaMariaAuer** [comment]
nur Research Article ?

**Comment by ChristophToegel** [comment]
Impact Faktor speichern 
Sonst keine FIlterung
