### ISSUE TITLE
JSON Art des Papers auslesen

### ISSUE THREAD

**Issue by JulianDietz** [ChristophToegel/PS-TextMining#60]
Kategorie des Papers auslesen und im JSON file Metadata.type speichern.
<li class="list-inline-item ">Short Communication&nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>&nbsp;</li>

<li class="list-inline-item ">Research Article&nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>&nbsp;</li>

**Comment by ChristophToegel** [comment]
Done, Push later

**Comment by ChristophToegel** [comment]
pushed cf0947fdc97301ebac94c2c4137ac7334e500305
