### ISSUE TITLE
Stakeholdertreffen mit Schmidt

### ISSUE THREAD

**Issue by ChristophToegel** [ChristophToegel/PS-TextMining#72]
Treffen etwa um den 16.-20.08.18

* Prototyp muss fertig sein
* Frontend muss erkennbar sein
* Die meisten Metriken müssen erfüllt sein

**Comment by ChristophToegel** [comment]
URL speichern zur erneuten Abfrage der Filter ? wenn ja wie und wie werden handselektierte Korpuse dann gespeichert (URL nicht möglich)

**Comment by ChristophToegel** [comment]
Wieso erledigt?
Das steht ja noch an. Ist das schon ausgemacht wann ?

**Comment by mbthebt** [comment]
14.8 - 12.00
